# Generated by Django 2.2 on 2020-10-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20201019_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='commission',
            field=models.FloatField(default='0.08', editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_last_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
