# Generated by Django 2.2 on 2020-10-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20201019_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='facility',
        ),
        migrations.AddField(
            model_name='estate',
            name='facility',
            field=models.ManyToManyField(null=True, to='rentals.Facility'),
        ),
    ]
