# Generated by Django 2.2 on 2020-10-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_auto_20201020_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='zone',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
