# Generated by Django 2.2 on 2020-10-21 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_auto_20201021_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='since_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='to_date',
        ),
    ]
