# Generated by Django 2.2 on 2020-10-23 01:20

from django.db import migrations
import rentals.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_auto_20201021_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=rentals.models.NameField(max_length=200),
        ),
    ]
