# Generated by Django 2.2 on 2020-10-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_auto_20201022_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
