# Generated by Django 2.2 on 2020-10-24 00:51

from django.db import migrations, models
import rentals.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_auto_20201024_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=rentals.models.NameField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estate',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_last_name',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
