# Generated by Django 2.2 on 2020-10-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_auto_20201024_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='image',
            field=models.ImageField(blank=True, upload_to='estate_images'),
        ),
    ]
